version: '3'
services:
  app:
    build: .
    volumes:
      - appdata:/usr/src/app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: twitter_db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local