version: '3'
services:
  ingestion:
    build: 
      context: .
      dockerfile: ./ingestion/Dockerfile
    volumes:
      - twitterdata:/usr/src/app
  trends_api:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - trendsdata:/usr/src/app

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    environment:
      MONGO_INITDB_DATABASE: twitter_db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27016:27017"
    logging:
      driver: none

volumes:
  mongodbdata:
    driver: local
  twitterdata:
    driver: local
  trendsdata:
    driver: local